import mongoose, { Schema } from 'mongoose';

/**
 * Schema for regional animal probability manifests.
 * 
 * This stores a ONE-TIME AI-generated probability map for each region.
 * The AI is called ONCE per region to generate probabilities for all animals.
 * User challenges are then selected using local code logic, NOT AI.
 */
const regionalChallengeSchema = new Schema(
  {
    // Unique key for the region, e.g., "richardson_texas", "dallas_texas"
    region_key: {
      type: String,
      required: true,
      unique: true,
      trim: true,
      lowercase: true,
      index: true,
    },
    // Human-readable location name
    location: {
      type: String,
      required: true,
      trim: true,
    },
    // Center coordinates for this region (for proximity matching)
    center: {
      latitude: { type: Number, required: true },
      longitude: { type: Number, required: true },
    },
    /**
     * The animal probability manifest - generated by AI ONCE per region.
     * Each entry contains:
     * - name: The animal's common name (matches Animal.commonName in DB)
     * - probability: 0-100 likelihood of spotting this animal in this region on a given day
     */
    animal_manifest: [
      {
        name: { type: String, required: true },
        probability: { type: Number, required: true, min: 0, max: 100 },
      },
    ],
    // Metadata about generation
    generated_by: {
      type: String,
      default: 'gemini-2.5-flash-lite',
    },
    // Raw response from AI for debugging
    raw_response: {
      type: Schema.Types.Mixed,
    },
  },
  { timestamps: true }
);

// Index for geospatial proximity queries
regionalChallengeSchema.index({ 'center.latitude': 1, 'center.longitude': 1 });

export const RegionalChallenge = mongoose.model('RegionalChallenge', regionalChallengeSchema);
