import { StyleSheet, Dimensions } from 'react-native';
import { Colors } from './Colors';

const SCREEN_WIDTH = Dimensions.get('window').width;


export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: Colors.light.background },
    header: {
        paddingTop: 50,
        paddingHorizontal: 16,
        paddingBottom: 12,
        backgroundColor: Colors.light.background,
        borderBottomWidth: 1,
        borderBottomColor: Colors.light.shadow,
        elevation: 2,
    },
    title: {
        fontSize: 28,
        fontWeight: '700',
        color: Colors.light.mainText,
        textAlign: 'center',
        marginBottom: 4,
    },
    subtitle: { marginTop: 4, fontSize: 14, color: Colors.light.darkNeutral },
    searchBox: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Colors.light.cardBackground,
        borderRadius: 10,
        paddingHorizontal: 12,
        marginTop: 12,
        marginBottom: 8,
        elevation: 1,
    },
    searchInput: { flex: 1, color: Colors.light.mainText, paddingVertical: 10 },
    tabsContainer: {
        flexDirection: 'row',
        marginVertical: 8,
        marginBottom: 4,
    },
    tabPercent: {
        color: Colors.light.darkNeutral,
        fontSize: 15,
        fontWeight: '600',
        marginTop: 2,
        textAlign: 'center',
    },
    tab: {
        paddingVertical: 8,
        paddingHorizontal: 18,
        borderRadius: 20,
        marginRight: 10,
        backgroundColor: Colors.light.cardBackground,
        elevation: 0,
    },
    tabActive: {
        backgroundColor: Colors.light.primaryGreen,
        elevation: 2,
    },
    tabText: {
        color: Colors.light.mainText,
        fontWeight: '500',
        fontSize: 16,
    },
    tabTextActive: {
        color: '#fff',
        fontWeight: '700',
    },
    sectionHeader: {
        backgroundColor: Colors.light.cardBackground,
        paddingVertical: 6,
        paddingHorizontal: 16,
        borderTopWidth: StyleSheet.hairlineWidth,
        borderTopColor: Colors.light.shadow,
        borderRadius: 10,
        marginBottom: 4,
        marginTop: 8,
    },
    sectionHeaderText: { color: Colors.light.mainText, fontWeight: '600', fontSize: 16 },
    grid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'flex-start',
        paddingHorizontal: 8,
        paddingTop: 8,
    },
    square: {
        width: "29%",
        margin: 8,
        aspectRatio: 1,
        borderRadius: 16,
        backgroundColor: Colors.light.itemBackground,
        alignItems: 'center',
        justifyContent: 'center',
        elevation: 2,
        shadowColor: Colors.light.shadow,
        shadowOpacity: 0.2,
        shadowRadius: 4,
        shadowOffset: { width: 0, height: 2 },
        borderWidth: 1,
        borderColor: Colors.light.shadow,
    },
    lockedSquare: {
        backgroundColor: Colors.light.lightGrey,
        opacity: 0.5,
        borderColor: Colors.light.darkNeutral,
    },
    animalImage: {
        width: 56,
        height: 56,
        borderRadius: 12,
        resizeMode: 'cover',
        marginBottom: 6,
        backgroundColor: Colors.light.softBeige,
        borderWidth: 1,
        borderColor: Colors.light.shadow,
    },
    silhouette: {
        width: "80%",
        height: 56,
        borderRadius: 12,
        backgroundColor: Colors.light.darkNeutral,
        marginBottom: 6,
        alignItems: 'center',
        justifyContent: 'center',
    },
    animalName: { color: Colors.light.mainText, fontSize: 13, textAlign: 'center' },
    empty: { color: Colors.light.darkNeutral, textAlign: 'center', marginTop: 40 },
    badgeRow: { flexDirection: 'row', alignItems: 'center', marginTop: 4 },
    spottedBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Colors.light.primaryGreen,
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
        marginLeft: 8
    },
    spottedBadgeText: { color: '#fff', fontSize: 12, marginLeft: 4, fontWeight: '600' },
    userBadge: { backgroundColor: Colors.light.accent },
    progressBarContainer: {
        width: '90%',
        alignSelf: 'center',
        height: 25,
        backgroundColor: Colors.light.lightGrey,
        borderRadius: 8,
        marginTop: 6,
        marginBottom: 2,
        overflow: 'hidden',
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: Colors.light.shadow,
    },
    progressBarFill: {
        height: '100%',
        backgroundColor: Colors.light.primaryGreen,
        borderRadius: 8,
    },
    progressBarText: {
        position: 'absolute',
        width: '100%',
        textAlign: 'center',
        color: Colors.light.mainText,
        fontWeight: '600',
        fontSize: 13,
    },
    swipeInfoContainer: {
        width: SCREEN_WIDTH - 32,
        height: '100%', // Fill available height
        minHeight: 600, // Increase minHeight for more content
        paddingHorizontal: 16,
        paddingVertical: 18,
        backgroundColor: Colors.light.cardBackground,
        borderRadius: 14,
        marginHorizontal: 0,
        elevation: 2,
        shadowColor: Colors.light.shadow,
        shadowOpacity: 0.15,
        shadowRadius: 6,
        shadowOffset: { width: 0, height: 2 },

    },
    swipeInfoTitle: {
        fontWeight: 'bold',
        fontSize: 17,
        color: Colors.light.mainText,
        marginBottom: 4,
        textAlign: 'left',
    },
    swipeInfoText: {
        color: Colors.light.darkNeutral,
        fontSize: 13,
        marginBottom: 2,
        textAlign: 'left',
    },
    swipeInfoLabel: {
        fontWeight: 'bold',
        color: Colors.light.mainText,
    },
    swipePageIndicator: {
        textAlign: 'center',
        color: Colors.light.darkNeutral,
        marginBottom: 6,
        fontSize: 13,
        fontWeight: '600',
    },
});

export const modalStyles = StyleSheet.create({
    backdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'flex-end' },
    sheet: {
        backgroundColor: Colors.light.cardBackground,
        paddingTop: 12,
        paddingHorizontal: 16,
        paddingBottom: 32,
        borderTopLeftRadius: 18,
        borderTopRightRadius: 18,
        height: '90%',
        width: '100%',
    },
    handle: { width: 50, height: 5, backgroundColor: Colors.light.darkNeutral, borderRadius: 3, alignSelf: 'center', marginBottom: 12 },
    sheetTitle: { color: Colors.light.mainText, fontSize: 18, fontWeight: '700', marginBottom: 4 },
    sheetSubtitle: { color: Colors.light.darkNeutral, fontSize: 12, marginBottom: 12 },
    sightingRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 10, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: Colors.light.shadow },
    thumb: { width: 54, height: 54, borderRadius: 8, backgroundColor: Colors.light.lightGrey, marginRight: 12 },
    cap: { color: Colors.light.mainText, flex: 1, fontSize: 13 },
    time: { color: Colors.light.darkNeutral, fontSize: 11, marginTop: 4 }
});