import { StyleSheet } from "react-native";
import { Colors } from "./Colors";

export const LoginScreenStyles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'flex-start',
        alignItems: 'center',
        backgroundColor: Colors.light.background,
        paddingTop: 100,
        paddingHorizontal: 20,
    },
    logo: {
        width: 260,
        height: 260,
        resizeMode: 'contain',
        marginBottom: 10,
    },
    inputContainer: {
        width: '100%',
        maxWidth: 400,
        height: 50,
        backgroundColor: Colors.light.cardBackground,
        borderRadius: 10,
        marginBottom: 15,
        borderWidth: 2,
        borderColor: Colors.light.secondaryGreen,
        flexDirection: 'row',
        alignItems: 'center',
        position: 'relative',
    },
    inputIcon: {
        marginLeft: 12,
        marginRight: 8,
    },
    inputWithIcon: {
        flex: 1,
        height: '100%',
        color: Colors.light.darkNeutral,
        fontSize: 16,
        paddingRight: 40,
    },
    eyeIcon: {
        position: 'absolute',
        right: 12,
        padding: 8,
    },
    input: {
        width: '100%',
        maxWidth: 400,
        height: 50,
        backgroundColor: Colors.light.cardBackground,
        borderRadius: 10,
        paddingHorizontal: 15,
        marginBottom: 15,
        borderWidth: 2,
        borderColor: Colors.light.secondaryGreen,
        color: Colors.light.darkNeutral,
        fontSize: 16,
    },
    button: {
        backgroundColor: Colors.light.primaryGreen,
        paddingVertical: 15,
        borderRadius: 10,
        width: '100%',
        maxWidth: 400,
        alignItems: 'center',
        shadowColor: Colors.light.shadow,
        shadowOpacity: 0.15,
        shadowRadius: 6,
        elevation: 2,
        marginTop: 8,
    },
    buttonContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
    },
    buttonText: {
        color: Colors.light.background,
        fontSize: 18,
        fontWeight: '600',
    },
    buttonTextLoading: {
        color: Colors.light.background,
        fontSize: 18,
        fontWeight: '600',
        marginLeft: 8,
    },
    dividerContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        width: '100%',
        maxWidth: 400,
        marginVertical: 20,
    },
    dividerLine: {
        flex: 1,
        height: 1,
        backgroundColor: '#d1d5db',
    },
    dividerText: {
        paddingHorizontal: 16,
        fontSize: 14,
        color: '#6b7280',
    },
    googleButton: {
        backgroundColor: '#ffffff',
        paddingVertical: 15,
        borderRadius: 10,
        width: '100%',
        maxWidth: 400,
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: '#d1d5db',
        shadowColor: Colors.light.shadow,
        shadowOpacity: 0.05,
        shadowRadius: 3,
        elevation: 1,
    },
    googleIcon: {
        width: 20,
        height: 20,
        marginRight: 8,
    },
    googleButtonText: {
        color: '#374151',
        fontSize: 16,
        fontWeight: '500',
    },
    footerLinks: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
        maxWidth: 400,
        marginTop: 24,
    },
    linkText: {
        color: Colors.light.primaryGreen,
        fontSize: 14,
        fontWeight: '500',
    },
});